### ISSUE TITLE
mathorcup的latex模板目录中附录的样式问题

### ISSUE THREAD

**Issue by 12312348** [sikouhjw/MathorCupmodeling#1]
求助大神：
我想把目录中的“附录一：问题一的matlab求解”改成只有“附录”，且目录中不显示附录中的其他section，应该怎么做呢？
望回复，谢谢。
![批注 2020-05-20 202253](https://user-images.githubusercontent.com/65545437/82449095-4425cf80-9add-11ea-9fa5-22f34ef6d451.png)

**Comment by sikouhjw** [comment]
正文的附录编不编号？
附录1：xxxxx
附录2：yyyyy
or
xxxxx
yyyyy

**Comment by 12312348** [comment]
编号的，第一种
![附录](https://user-images.githubusercontent.com/65545437/82449572-037a8600-9ade-11ea-8c52-01ec999736ad.png)

**Comment by sikouhjw** [comment]
将
```tex
\newcounter{appnumber}
\setcounter{appnumber}{0}
\newcommand{\appsection}[1]{\stepcounter{appnumber}\begin{flushleft}\zihao{-4}\heiti 附录 \theappnumber：#1\end{flushleft}}
```
写到导言区，用 `\appsection{问题一的 MATLAB 代码}` 写附录的 `section`

-----------
https://github.com/sikouhjw/MathorCupmodeling/blob/40c89e7d33878cc58ecc69b0e20ce8894e9426c3/example.tex#L135-L137
改成
```tex
\begin{center}
	\heiti\zihao{4} 附\hspace{1pc}录
\end{center}
\phantomsection
\addcontentsline{toc}{section}{附录}
```

**Comment by 12312348** [comment]
谢谢您，附录添加上了，但是目录里还有“附录一：”，有没有什么方法可以去掉呢？
![截图](https://user-images.githubusercontent.com/65545437/82453416-13489900-9ae3-11ea-99df-746dbf133d8c.png)

**Comment by sikouhjw** [comment]
麻烦好好看我的回答

**Comment by 12312348** [comment]
不好意思，改过来了，太谢谢你啦！
