### ISSUE TITLE
关于在mathorcup的latex模板中加入推荐信的问题

### ISSUE THREAD

**Issue by 12312348** [sikouhjw/MathorCupmodeling#2]
大神您好，想问一下mathorcup的latex模板怎样在正文中加入推荐信呢？

**Comment by sikouhjw** [comment]
> 大神您好，想问一下mathorcup的latex模板怎样在正文中加入推荐信呢？

推荐信是什么？一封信？跟美赛那个类似吗？给个格式/图片

**Comment by 12312348** [comment]
![推荐信](https://user-images.githubusercontent.com/65545437/82618868-d83f8600-9c06-11ea-9944-5335f31944bc.png)
他只说写一封推荐信，没说具体格式要求，我觉得像这种的就可以，再加上此致，敬礼

**Comment by sikouhjw** [comment]
> ![推荐信](https://user-images.githubusercontent.com/65545437/82618868-d83f8600-9c06-11ea-9944-5335f31944bc.png)
> 他只说写一封推荐信，没说具体格式要求，我觉得像这种的就可以，再加上此致，敬礼

用对齐环境就好了
```tex
\begin{center} 居中 \end{center}
\begin{flushleft} 左对齐 \end{flushleft}
\begin{flushright} 右对齐 \end{flushright}
```
自己试试吧

**Comment by 12312348** [comment]
好的我试一下，谢谢您
