### ISSUE TITLE
关于mathorcuplatex模版的附录问题

### ISSUE THREAD

**Issue by 12312348** [sikouhjw/MathorCupmodeling#4]
![附录问题](https://user-images.githubusercontent.com/65545437/82749435-d1b63780-9ddb-11ea-8a9e-6cfd7574ffe1.png)
大神，我想问一下：
1、我在附录一插入了十多张图片，怎样把附录二放到所有图片的后面呢（它总是在第一页的最后）
2、图片都是转.eps，为什么有的图片会出现这样框线不完整的情况呢
麻烦您了

**Comment by sikouhjw** [comment]
> 1、我在附录一插入了十多张图片，怎样把附录二放到所有图片的后面呢（它总是在第一页的最后）

在附录二前加 `\FloatBarrier`
> 2、图片都是转.eps，为什么有的图片会出现这样框线不完整的情况呢

结论是用 `pdf` 文件作为图片格式，在导出的时候选择 `pdf`，而不是 `eps` 格式，详看我的博文《[关于 .eps 格式图片的一些东西](https://sikouhjw.gitee.io/2020/03/16/2020-03-16-eps/)》

**Comment by 12312348** [comment]
好的，谢谢您
