### ISSUE TITLE
可以考虑添加overleaf适配

### ISSUE THREAD

**Issue by Andrew82106** [sikouhjw/MathorCupmodeling#6]
本模版在overleaf中使用MathorCupmodeling.cls文件时，第38行会报错：
```
\setCJKmainfont[Mapping=fullwidth-stop]{SimSun}
```
需要将其注释掉
另，Mathorcup的参考文献需要用gbt7714格式的引用，可以考虑通过添加gbt7714-numerical.bst实现，并且使用bib管理文献

**Comment by sikouhjw** [comment]
这份模板是很久之前写的，不打算更新了
